# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "client01"

  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "cliente01_ubuntu16"
    vbox.memory = 512
    vbox.cpus = 1
  end

  #Provision
  config.vm.provision "shell", inline: "ping -c 4 www.google.es"
end
